#service.yaml

apiVersion: v1
kind: Service
metadata:
  name: recruitment-rank-app
spec:
  type: LoadBalancer
  selector:
    app: recruitment-rank-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9696