apiVersion: v1
kind: Service
metadata:
  name: recruitment-rank-app-nodeport
spec:
  type: NodePort
  selector:
    app: recruitment-rank-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9696