apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-nodeport
spec:
  type: NodePort
  selector:
    app: flask-app-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000